---
kind: pipeline
name: default

steps:
  - name: Wait for services to be ready
    image: jwilder/dockerize
    commands:
      - dockerize -wait tcp://database:3306 -wait http://vault:8200 -timeout 30s

  - name: Run rspec
    image: ruby:2.6.5
    environment:
      DATABASE_HOST: database
      RAILS_ENV: test
      VAULT_ADDR: http://vault:8200
    commands:
      - gem update bundler
      - bundle --jobs $(nproc)
      - rake db:create db:migrate
      - rspec spec
    volumes:
      - name: gem-cache
        path: /root/.gem
      - name: bundler-cache
        path: /usr/local/bundle

  - name: Bump and tag
    image: quay.io/openware/sdk-citools:2.3.1
    environment:
      BOT_NAME: Kite
      BOT_EMAIL: kite-bot@heliostech.fr
      BOT_USERNAME: kite-bot
      BRANCH_NAME: ${DRONE_BRANCH}
      REPO_NAME: ${DRONE_REPO}
      GITHUB_API_KEY:
        from_secret: kite_bot_key
    commands:
      - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:prebuild
    when:
      branch:
        - master

  - name: Publish to Gitolite
    image: alpine/git
    environment:
      GITOLITE_KEY:
        from_secret: gitolite_rsa_key_b64
    commands:
      - mkdir -p ~/.ssh
      - echo $GITOLITE_KEY | base64 -d > ~/.ssh/id_rsa
      - chmod 0600 ~/.ssh/id_rsa
      - git remote add gitolite git@git.openware.com:arke
      - GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git push -f gitolite HEAD:master


  - name: "GCR Docker build and push"
    image: plugins/gcr
    settings:
      repo:
        from_secret: gcr_repo_first
      json_key:
        from_secret: gcr_creds_base64_first
    when:
      branch:
        - master
    volumes:
      - name: gem-cache
        path: /root/.gem
      - name: bundler-cache
        path: /usr/local/bundle

  - name: "Push to Openware Registry"
    image: plugins/docker
    settings:
      username:
        from_secret: ow_registry_username
      password:
        from_secret: ow_registry_password
      repo: reg.openware.work/openware/arke
      registry: reg.openware.work
    when:
      branch:
        - master
    volumes:
      - name: gem-cache
        path: /root/.gem
      - name: bundler-cache
        path: /usr/local/bundle

  - name: "Push image to Quay.io"
    image: plugins/docker
    settings:
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
      repo: quay.io/openware/arke
      registry: quay.io
    when:
      branch:
        - master

  - name: Push and Notify
    image: quay.io/openware/sdk-citools:2.3.1
    environment:
      BOT_USERNAME: kite-bot
      BOT_NAME: Kite Bot
      BOT_EMAIL: kite-bot@heliostech.fr
      REPO_NAME: ${DRONE_REPO}
      BRANCH_NAME: ${DRONE_BRANCH}
      SDK_BRANCH: ${DRONE_BRANCH}
      TELEGRAM_BOT_TOKEN:
        from_secret: telegram_bot_token
      TELEGRAM_CHAT_ID:
        from_secret: telegram_chat_id
      SLACK_TOKEN:
        from_secret: slack_token
      SLACK_CHANNEL:
        from_secret: slack_channel
      GITHUB_API_KEY:
        from_secret: kite_bot_key
    commands:
      - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:postbuild[/drone/src]
    when:
      branch:
        - master

services:
- name: database
  image: mariadb
  ports:
    - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

- name: vault
  image: vault:0.11.4
  ports:
    - 8200
  environment:
    SKIP_SETCAP: 1
    VAULT_TOKEN: changeme
    VAULT_DEV_ROOT_TOKEN_ID: changeme
    VAULT_ADDR: http://vault:8200

volumes:
  - name: gem-cache
    host:
      path: /var/cache/drone/arke-gem
  - name: bundler-cache
    host:
      path: /var/cache/drone/arke-bundler

trigger:
  event:
    - push

image_pull_secrets:
  - dockerconfigjson
