---
kind: pipeline
name: default

steps:
  - name: test
    image: ruby:2.6.5
    commands:
      - gem update bundler
      - bundle --jobs $(nproc)
      - rspec spec
    volumes:
      - name: gem-cache
        path: /root/.gem
      - name: bundler-cache
        path: /usr/local/bundle

  - name: tag-snapshot
    image: quay.io/openware/sdk-citools:2.6.7
    environment:
      BOT_NAME: Kite
      BOT_EMAIL: kite-bot@heliostech.fr
      BOT_USERNAME: kite-bot
      BRANCH_NAME: master
      REPO_NAME: ${DRONE_REPO}
      GITHUB_API_KEY:
        from_secret: kite_bot_key
    commands:
      - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:prebuild
    when:
      branch:
        - "master"
        - "integration/*"

  - name: tag-stable
    image: quay.io/openware/sdk-citools:2.6.5
    environment:
      BOT_NAME: Kite
      BOT_EMAIL: kite-bot@heliostech.fr
      BOT_USERNAME: kite-bot
      BRANCH_NAME: ${DRONE_BRANCH}
      REPO_NAME: ${DRONE_REPO}
      GITHUB_API_KEY:
        from_secret: kite_bot_key
    commands:
      - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:prebuild
    when:
      branch:
        - "*-stable"

  - name: git-push-gitolite
    image: alpine/git
    environment:
      GITOLITE_KEY:
        from_secret: gitolite_rsa_key_b64
    commands:
      - mkdir -p ~/.ssh
      - echo $GITOLITE_KEY | base64 -d > ~/.ssh/id_rsa
      - chmod 0600 ~/.ssh/id_rsa
      - git remote add gitolite git@git.openware.com:arke
      - GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git push -f gitolite HEAD:master

  - name: docker-build
    image: plugins/docker
    settings:
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
      repo: quay.io/openware/arke
      registry: quay.io
    when:
      branch:
        - "master"
        - "*-stable"
        - "integration/*"

  - name: sdk-postbuild
    image: quay.io/openware/sdk-citools:2.6.7
    environment:
      BOT_USERNAME: kite-bot
      BOT_NAME: Kite Bot
      BOT_EMAIL: kite-bot@heliostech.fr
      REPO_NAME: ${DRONE_REPO}
      BRANCH_NAME: ${DRONE_BRANCH}
      SDK_BRANCH: ${DRONE_BRANCH}
      TELEGRAM_BOT_TOKEN:
        from_secret: telegram_bot_token
      TELEGRAM_CHAT_ID:
        from_secret: telegram_chat_id
      SLACK_TOKEN:
        from_secret: slack_token
      SLACK_CHANNEL:
        from_secret: slack_channel
      GITHUB_API_KEY:
        from_secret: kite_bot_key
    commands:
      - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:postbuild[/drone/src]
    when:
      branch:
        - "master"
        - "*-stable"

volumes:
  - name: gem-cache
    host:
      path: /var/cache/drone/arke-gem
  - name: bundler-cache
    host:
      path: /var/cache/drone/arke-bundler

trigger:
  event:
    - push

image_pull_secrets:
  - dockerconfigjson
