# frozen_string_literal: true

require "clamp"
require "rbtree"
require "json"
require "openssl"
require "ostruct"
require "yaml"
require "colorize"
require "em-synchrony"
require "em-synchrony/em-http"
require "faraday"
require "faraday_middleware"
require "faye/websocket"
require "bigdecimal"
require "bigdecimal/util"

require "binance"
require "bitx"
require "rack"

module Arke; end

require "arke/helpers/precision"
require "arke/helpers/commands"
require "arke/helpers/price_points"
require "arke/helpers/spread"
require "arke/helpers/flags"
require "arke/helpers/orderbook"
require "arke/helpers/array"

require "arke/configuration"
require "arke/log"
require "arke/reactor"
require "arke/exchange"
require "arke/strategy"
require "arke/models/market"
require "arke/models/action"
require "arke/models/order"
require "arke/models/trade"
require "arke/models/kline"
require "arke/models/ticker"
require "arke/models/price_point"
require "arke/fx/static"
require "arke/fx/fixer"
require "arke/action_executor"
require "arke/scheduler/simple"
require "arke/scheduler/smart"

require "arke/plugins/base"
require "arke/plugins/limit_balance"

require "arke/orderbook/base"
require "arke/orderbook/orderbook"
require "arke/orderbook/aggregated"
require "arke/orderbook/open_orders"
require "arke/orderbook/generator"

require "arke/strategy/base"
require "arke/strategy/copy"
require "arke/strategy/fixedprice"
require "arke/strategy/microtrades_copy"
require "arke/strategy/microtrades_market"
require "arke/strategy/microtrades"
require "arke/strategy/orderback"
require "arke/strategy/circuitbraker"
require "arke/strategy/candle_sampling"
require "arke/strategy/simple_copy"
require "arke/strategy/skew"

require "arke/exchange/base"
require "arke/exchange/binance"
require "arke/exchange/bitfaker"
require "arke/exchange/bitfinex"
require "arke/exchange/hitbtc"
require "arke/exchange/huobi"
require "arke/exchange/kraken"
require "arke/exchange/luno"
require "arke/exchange/okex"
require "arke/exchange/opendax"
require "arke/exchange/finex"
require "arke/exchange/rubykube"
require "arke/exchange/valr"

require "arke/command"
require "arke/command/order"
require "arke/command/show"
require "arke/command/start"
require "arke/command/version"
require "arke/command/root"
