log_level: INFO

shared_params:
  markets: [BTCUSDT, ETHUSDT, LTCUSDT, ETHBTC, LTCBTC, BATETH, LINKETH, OMGETH, LTCETH, STEBTC, STEETH, STELTC, STEUSDT]

jobs:

  # - extract: Tickers
  #   process:
  #     - load: TickersWriter
  #     - load:
  #         AMQP:
  #           exchange: arke.events.ranger

  # - extract: Kline
  #   process:
  #     - load: KlineWriter
  #     - load:
  #         AMQP:
  #           exchange: arke.events.ranger

  # Store non sampled binance trades
  # - extract:
  #     Binance:
  #       listen:
  #         - public_trades
  #   process:
  #     - transform:
  #         - Debug
  #       load:
  #         Influx:
  #           measurment: trades
  # - extract:
  #     Binance:
  #       listen:
  #         - public_trades
  #   transform:
  #    - Sample:
  #        ratio: 0.2  
  #   process:
  #     - load:
  #         Influx:
  #           measurment: trades
  #     - load:
  #         AMQP:
  #           exchange: arke.events.ranger

  # # Sample binance trades, store in influx and forward to arke AMQP
  # - extract:
  #     Binance:
  #       listen:
  #         - public_trades
  #   transform:
  #     - Sample:
  #         ratio: 0.1
  #     - Debug:
  #         id: pre_process
  #     - Generic:
  #         field: market
  #         apply: downcase!
  #   process:
  #     # - load:
  #     #     influx:
  #     #       measurment: trades-sampled
  #     - transform:
  #       - Debug:
  #           id: post_process
  #       load:
  #         PeatioAMQP:
  #           exchange: peatio.events.ranger


  # Listen peatio trades, store in influx and forward to arke AMQP
  - extract:
      PeatioAMQP:
        exchange: peatio.events.ranger
        events:
          - {type: public, event: trades}
    process:
      - load:
          Influx:
            measurment: trades


  # Forward peatio events except tickers and klines
  - extract:
      AMQP:
        exchange: peatio.events.ranger
        events:
          - {type: public, event: update}
          - {type: public, event: trades}
          - {type: public, event: ob-inc}
          - {type: private}
    process:
      - load: Print
      - load:
          AMQP:
            exchange: arke.events.ranger
